using System;
using System.Reflection;
using System.EnterpriseServices;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("SpecExpress.Test")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyProductAttribute("SpecExpress.Test")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("1.1.41649")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright, Alan Baker 2009")]

