//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecExpress.MessageStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecExpress.MessageStore.RuleErrorMessages", typeof(RuleErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should only contain letters..
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be between {floor} and {ceiling}..
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} does not contain {PropertyValue}..
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should contain {countEquals} items..
        /// </summary>
        internal static string CountEqualTo {
            get {
                return ResourceManager.GetString("CountEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should contain greater than {countGreaterThan} items..
        /// </summary>
        internal static string CountGreaterThan {
            get {
                return ResourceManager.GetString("CountGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should contain greater than or equal to  {countGreaterThanEqualTo} items..
        /// </summary>
        internal static string CountGreaterThanEqualTo {
            get {
                return ResourceManager.GetString("CountGreaterThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should contain less than {countLessThan} items..
        /// </summary>
        internal static string CountLessThan {
            get {
                return ResourceManager.GetString("CountLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should contain less or equal to {countLessThanEqualTo} items..
        /// </summary>
        internal static string CountLessThanEqualTo {
            get {
                return ResourceManager.GetString("CountLessThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must equal {equalTo}..
        /// </summary>
        internal static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than {greaterThan}..
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than or equal to {greaterThanEqualTo}..
        /// </summary>
        internal static string GreaterThanEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be empty..
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be false..
        /// </summary>
        internal static string IsFalse {
            get {
                return ResourceManager.GetString("IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be in the future..
        /// </summary>
        internal static string IsInFuture {
            get {
                return ResourceManager.GetString("IsInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be in the past..
        /// </summary>
        internal static string IsInPast {
            get {
                return ResourceManager.GetString("IsInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not a valid value..
        /// </summary>
        internal static string IsInSet {
            get {
                return ResourceManager.GetString("IsInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be true..
        /// </summary>
        internal static string IsTrue {
            get {
                return ResourceManager.GetString("IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should be unique.  The duplicates of the following: {itemsAreUnique}.
        /// </summary>
        internal static string ItemsAreUnique {
            get {
                return ResourceManager.GetString("ItemsAreUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be between {min} and {max} characters..
        /// </summary>
        internal static string LengthBetween {
            get {
                return ResourceManager.GetString("LengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be {0} character(s)..
        /// </summary>
        internal static string LengthEqualTo {
            get {
                return ResourceManager.GetString("LengthEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than {0}..
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than or equal to {0}..
        /// </summary>
        internal static string LessThanEqualTo {
            get {
                return ResourceManager.GetString("LessThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in {PropertyName} does not meet the pattern of &apos;{0}&apos;..
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than {0} characters..
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than {0} characters..
        /// </summary>
        internal static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain letters..
        /// </summary>
        internal static string Not_Alpha {
            get {
                return ResourceManager.GetString("Not_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be between {0} and {1}..
        /// </summary>
        internal static string Not_Between {
            get {
                return ResourceManager.GetString("Not_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} contains {PropertyValue}..
        /// </summary>
        internal static string Not_Contains {
            get {
                return ResourceManager.GetString("Not_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain {0} items..
        /// </summary>
        internal static string Not_CountEqualTo {
            get {
                return ResourceManager.GetString("Not_CountEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain greater than {0} items..
        /// </summary>
        internal static string Not_CountGreaterThan {
            get {
                return ResourceManager.GetString("Not_CountGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain greater than or equal to {0} items..
        /// </summary>
        internal static string Not_CountGreaterThanEqualTo {
            get {
                return ResourceManager.GetString("Not_CountGreaterThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain less than {0} items..
        /// </summary>
        internal static string Not_CountLessThan {
            get {
                return ResourceManager.GetString("Not_CountLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain less or equal to {0} items..
        /// </summary>
        internal static string Not_CountLessThanEqualTo {
            get {
                return ResourceManager.GetString("Not_CountLessThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not equal {0}.  You entered {PropertyValue}..
        /// </summary>
        internal static string Not_EqualTo {
            get {
                return ResourceManager.GetString("Not_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be greater than {0}..
        /// </summary>
        internal static string Not_GreaterThan {
            get {
                return ResourceManager.GetString("Not_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be greater than or equal to {0}..
        /// </summary>
        internal static string Not_GreaterThanEqualTo {
            get {
                return ResourceManager.GetString("Not_GreaterThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be empty..
        /// </summary>
        internal static string Not_IsEmpty {
            get {
                return ResourceManager.GetString("Not_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be false..
        /// </summary>
        internal static string Not_IsFalse {
            get {
                return ResourceManager.GetString("Not_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be in the future. .
        /// </summary>
        internal static string Not_IsInFuture {
            get {
                return ResourceManager.GetString("Not_IsInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be in the past..
        /// </summary>
        internal static string Not_IsInPast {
            get {
                return ResourceManager.GetString("Not_IsInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not a valid value..
        /// </summary>
        internal static string Not_IsInSet {
            get {
                return ResourceManager.GetString("Not_IsInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be true..
        /// </summary>
        internal static string Not_IsTrue {
            get {
                return ResourceManager.GetString("Not_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not be unique..
        /// </summary>
        internal static string Not_ItemsAreUnique {
            get {
                return ResourceManager.GetString("Not_ItemsAreUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be between {0} and {1} characters..
        /// </summary>
        internal static string Not_LengthBetween {
            get {
                return ResourceManager.GetString("Not_LengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not be {0} characters..
        /// </summary>
        internal static string Not_LengthEqualTo {
            get {
                return ResourceManager.GetString("Not_LengthEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be less than {0}..
        /// </summary>
        internal static string Not_LessThan {
            get {
                return ResourceManager.GetString("Not_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be less than or equal to {0}..
        /// </summary>
        internal static string Not_LessThanEqualTo {
            get {
                return ResourceManager.GetString("Not_LessThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value in {PropertyName} must not meet the pattern of &apos;{0}&apos;..
        /// </summary>
        internal static string Not_Matches {
            get {
                return ResourceManager.GetString("Not_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be less than {0} characters..
        /// </summary>
        internal static string Not_MaxLength {
            get {
                return ResourceManager.GetString("Not_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not be greater than {0} characters..
        /// </summary>
        internal static string Not_MinLength {
            get {
                return ResourceManager.GetString("Not_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not contain numbers..
        /// </summary>
        internal static string Not_Numeric {
            get {
                return ResourceManager.GetString("Not_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should only contain numbers..
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is required..
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is invalid..
        /// </summary>
        internal static string SpecificationRule {
            get {
                return ResourceManager.GetString("SpecificationRule", resourceCulture);
            }
        }
    }
}
